services:

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crud_example
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  config-server:
    build:
      context: .
      target: config-server
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: git
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  discovery-service:
    build:
      context: .
      target: discovery-service
    ports:
      - "8085:8085"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

  api-gateway:
    build:
      context: .
      target: api-gateway
    ports:
      - "8084:8084"
    depends_on:
      - config-server
      - discovery-service
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka

  crud-api-service:
    build:
      context: .
      target: crud-api
    ports:
      - "8080:8080"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/crud_example
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - config-server
      - discovery-service
      - kafka
      - postgres-db

  kafka-notification-impl:
    build:
      context: .
      target: kafka-notification-impl
    ports:
      - "8081:8081"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
    depends_on:
      - config-server
      - discovery-service
      - kafka